### ISSUE TITLE
Feature Request: JSON Syntax Highlighting

### ISSUE THREAD

**Issue by ethib137** [iaseth/josn#1]
Cool Project! I like what you've done thus far. Quickly printing only a single part of a large JSON is really helpful!

Is there currently any way to include syntax highlighting in the JSON that's printed, or do you have any plans to add syntax highlighting in the future?

**Comment by iaseth** [comment]
JOSN by default uses `JSON.stringify()` for printing, which does not have highlighting.

But you can add the `--console` (`-c`) or `--table` (`-t`) flags to force it to use `console.log()` or `console.table()` for printing, both of which have some default highlighting. For example, using one of the demos, you can do
```
josn @colors.json colors -c
```
```
josn @colors.json colors -t
```
A complete list of current flags is available [here](https://github.com/iaseth/josn/blob/master/src/cmdoptions.ts).
Not all of them are implemented yet.

I often break stuff, so always try to use the latest version with
```
npm i -g josn-cli@latest
```

Thanks for asking! I didn't know there are people other than me using this!

**Comment by iaseth** [comment]
JOSN now uses `console.log(obj)` by default, no need for the `-c` flag.

If you want the older `console.log(JSON.stringify(obj))` behavior,, supply the `--plaintext` (`-p`) flag.
For specifying indentation, use `-s` for `2 spaces`, `-S` for `4 spaces` and `-T` for `Tabs`. 
Default indentation is `Tabs`.
